[package]
name = "async_smux"
version = "0.2.1"
authors = ["black-binary <blackbinary@qq.com>"]
description = "Asynchronous smux multiplexing library"
license = "MIT"
edition = "2018"

[dependencies]
futures = "0.3"
bytes = "0.6"
rand = "0.7"
log = "0.4"
async-channel = "1.5"
async-lock = "2.3"
futures-lite = "1.11"

[dev-dependencies]
smol = "1"
async-std = "1"
bytes = "0.6"
env_logger = "0.8"
criterion = "0.3"
pprof = { version = "0.3", features = ["flamegraph"] } 

[profile.release]
debug = true

[[bench]]
name = "smol"
harness = false